Controllers/BookCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryManagementSystem.Data;
using LibraryManagementSystem.Models;

namespace LibraryManagementSystem.Controllers
{
    public class BookCategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BookCategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: BookCategory
        //show all data
        public IActionResult Index()
        {
            //select * from bookcategory
            //labmda expression
            return View(_context.BookCategory.ToList());
        }

        // GET: BookCategory/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

//select top 1 * from Bookcategory where id = 
            var bookCategoryModel =  _context.BookCategory.FirstOrDefault(m => m.Id == id);
            if (bookCategoryModel == null)
            {
                return NotFound();
            }

            return View(bookCategoryModel);
        }

        // GET: BookCategory/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BookCategory/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookCategoryModel bookCategoryModel)
        {
            if (ModelState.IsValid)
            {
                //insert into
                _context.Add(bookCategoryModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bookCategoryModel);
        }

        // GET: BookCategory/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookCategoryModel = await _context.BookCategory.FindAsync(id);
            if (bookCategoryModel == null)
            {
                return NotFound();
            }
            return View(bookCategoryModel);
        }

        // POST: BookCategory/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] BookCategoryModel bookCategoryModel)
        {
            if (id != bookCategoryModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bookCategoryModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookCategoryModelExists(bookCategoryModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bookCategoryModel);
        }

        // GET: BookCategory/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookCategoryModel = await _context.BookCategory
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bookCategoryModel == null)
            {
                return NotFound();
            }

            return View(bookCategoryModel);
        }

        // POST: BookCategory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bookCategoryModel = await _context.BookCategory.FindAsync(id);
            _context.BookCategory.Remove(bookCategoryModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookCategoryModelExists(int id)
        {
            return _context.BookCategory.Any(e => e.Id == id);
        }
    }
}

Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryManagementSystem.Data;
using LibraryManagementSystem.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace LibraryManagementSystem.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _env;

        public BookController(ApplicationDbContext context , IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        // GET: Book
        public IActionResult Index()
        {
            var applicationDbContext = _context.Book.Include(b => b.BookCategory)
                .Include(b => b.Publisher).ToList();
            return View(applicationDbContext);
     
        }

        // GET: Book/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookModel = await _context.Book
                .Include(b => b.BookCategory)
                .Include(b => b.Publisher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bookModel == null)
            {
                return NotFound();
            }

            return View(bookModel);
        }

        // GET: Book/Create
        public IActionResult Create()
        {
            ViewData["BookTypeId"] = new SelectList(_context.BookCategory, "Id", "Name");
            ViewData["PublisherId"] = new SelectList(_context.Publisher, "Id", "Name");
            return View();
        }

        // POST: Book/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Author,Price,Available,PublisherId,BookTypeId")] BookModel bookModel, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                if(file != null && file.Length >0)
                {
                    fileName = file.FileName;
                    var path = Path.Combine(_env.WebRootPath, "uploads", file.FileName);
                    file.CopyTo(new FileStream(path, FileMode.Create));
                }
                bookModel.FileName = fileName;
                _context.Add(bookModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookTypeId"] = new SelectList(_context.BookCategory, "Id", "Name", bookModel.BookTypeId);
            ViewData["PublisherId"] = new SelectList(_context.Publisher, "Id", "Name", bookModel.PublisherId);
            return View(bookModel);
        }

        // GET: Book/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookModel = await _context.Book.FindAsync(id);
            if (bookModel == null)
            {
                return NotFound();
            }
            ViewData["BookTypeId"] = new SelectList(_context.BookCategory, "Id", "Name", bookModel.BookTypeId);
            ViewData["PublisherId"] = new SelectList(_context.Publisher, "Id", "Name", bookModel.PublisherId);
            return View(bookModel);
        }

        // POST: Book/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,BookModel bookModel, IFormFile file)
        {
            if (id != bookModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string fileName = string.Empty;
                    if (file != null && file.Length > 0)
                    {
                        fileName = file.FileName;
                        var path = Path.Combine(_env.WebRootPath, "uploads", file.FileName);
                        file.CopyTo(new FileStream(path, FileMode.Create));
                    }
                    bookModel.FileName = fileName;
                    _context.Update(bookModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookModelExists(bookModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookTypeNaId"] = new SelectList(_context.BookCategory, "Id", "Name", bookModel.BookTypeId);
            ViewData["PublisherId"] = new SelectList(_context.Publisher, "Id", "Name", bookModel.PublisherId);
            return View(bookModel);
        }

        // GET: Book/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookModel = await _context.Book
                .Include(b => b.BookCategory)
                .Include(b => b.Publisher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bookModel == null)
            {
                return NotFound();
            }

            return View(bookModel);
        }

        // POST: Book/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bookModel = await _context.Book.FindAsync(id);
            _context.Book.Remove(bookModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookModelExists(int id)
        {
            return _context.Book.Any(e => e.Id == id);
        }
    }
}

Views/Book/Create.cshtml
@model LibraryManagementSystem.Models.BookModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BookModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublisherId" class="control-label">Publisher</label>
                <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.PublisherId"></select>
                <a asp-controller="publisher" asp-action="index" target="_blank">Go to publisher panel</a>
            </div>
            <div class="form-group">
                <label asp-for="BookTypeId" class="control-label">Book category</label>
                <select asp-for="BookTypeId" class="form-control" asp-items="ViewBag.BookTypeId"></select>
                <a asp-controller="BookCategory" asp-action="index" target="_blank">Go to category panel</a>
            </div>
            <div class="form-group">
                <label>Select Image</label>
                <input type="file" name="file" />
            </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Book/Delete.cshtml
@model LibraryManagementSystem.Models.BookModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BookModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookCategory.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Book/Details.cshtml
@model LibraryManagementSystem.Models.BookModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>BookModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookCategory.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Book/Edit.cshtml
@model LibraryManagementSystem.Models.BookModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BookModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublisherId" class="control-label"></label>
                <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.PublisherId"></select>
                <span asp-validation-for="PublisherId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookTypeId" class="control-label"></label>
                <select asp-for="BookTypeId" class="form-control" asp-items="ViewBag.BookTypeId"></select>
                <span asp-validation-for="BookTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Select Image</label>
                <input type="file" name="file" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Book/Index.cshtml
@model IEnumerable<LibraryManagementSystem.Models.BookModel>

@{
    ViewData["Title"] = "Index";
}




<h1>Books</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>


<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-lg-3">
            <div class="card" style="width: 14rem;">
                @if (string.IsNullOrEmpty(item.FileName))
                {
                    <img src="~/Images/image1.jpg" class="card-img-top" alt="Image..." height="150" width="130">

                }
                else
                {
                    <img src="~/uploads/@item.FileName" class="card-img-top" alt="Image..."height="150" width="130">

                }
                <div class="card-body">
                    <p class="card-text"></p>
                </div>
                <div class="card-body">
                    <p class="card-title">Book Name   : @item.Name</p>
                    <p class="card-title">Author Name : @item.Author</p>
                    <p class="card-title">Book Price  : @item.Price</p>
                    <p class="card-title">Quantity    : @item.Quantity</p>
                    
                    <p class="card-title">BookCategory : @item.BookCategory.Name</p>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>

                </div>
            </div>
        </div>
    }

</div>


